import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import {documentTotals, money} from "./calc";

const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const typeLabel=t=>({invoice:"INVOICE",estimate:"ESTIMATE",change_order:"CHANGE ORDER"}[t]||String(t||"").toUpperCase());

export function documentHtml(state,doc){
 const brand=state.brands.find(b=>b.id===doc.brandId)||{};
 const job=state.jobs.find(j=>j.id===doc.jobId)||{};
 const customer=state.customers.find(c=>c.id===job.customerId)||{};
 const t=documentTotals(doc,state.settings);
 const rows=(doc.items||[]).map(i=>`<tr><td><b>${esc(i.description)}</b>${i.notes?`<div class="muted note">${esc(i.notes)}</div>`:""}</td><td class="r">${esc(i.qty)}${i.unit?` ${esc(i.unit)}`:""}</td><td class="r">${money(i.unitPrice)}</td><td class="r"><b>${money(Number(i.qty)*Number(i.unitPrice))}</b></td></tr>`).join("");
 const logo=brand.logoUri?`<img class="logo" src="${esc(brand.logoUri)}">`:"";
 const gst=Number(t.gst||0)>0?`<div><span>GST</span><span>${money(t.gst)}</span></div>`:"";
 const pst=Number(t.pst||0)>0?`<div><span>PST</span><span>${money(t.pst)}</span></div>`:"";
 return `<!doctype html><html><head><meta charset="utf-8"><style>
 @page{margin:0}*{box-sizing:border-box}body{margin:0;color:#222;font:12px -apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}.page{padding:46px 50px}.top{display:flex;justify-content:space-between;align-items:flex-start}.logo{max-width:175px;max-height:75px;object-fit:contain;margin-bottom:10px}.brand{font-size:17px;font-weight:700}.contact,.muted{color:#6b6f76}.contact{line-height:1.55;margin-top:4px}.doctype{text-align:right}.doctype h1{font-size:32px;font-weight:400;margin:0 0 8px}.number{font-size:14px;font-weight:700}.date{color:#6b6f76;margin-top:5px}.rule{border-top:1px solid #d9dadd;margin:27px 0 23px}.info{display:flex;justify-content:space-between;gap:30px}.label{font-size:9px;letter-spacing:.9px;text-transform:uppercase;color:#777;font-weight:700;margin-bottom:7px}.bill{font-size:13px;line-height:1.55}.job{text-align:right;max-width:46%}.jobtitle{font-size:14px;font-weight:700}.jobnote{margin-top:5px;line-height:1.45;color:#666}table{width:100%;border-collapse:collapse;margin-top:30px}thead{background:#f2f3f5}th{font-size:9px;text-transform:uppercase;letter-spacing:.6px;color:#555;padding:10px 9px;text-align:left;border-bottom:1px solid #d9dadd}td{padding:12px 9px;border-bottom:1px solid #e5e6e8;vertical-align:top}.r{text-align:right;white-space:nowrap}.note{font-size:10px;margin-top:3px}.totals{width:310px;margin:24px 0 0 auto}.totals div{display:flex;justify-content:space-between;padding:5px 2px}.grand{font-size:19px;font-weight:700;border-top:1px solid #aeb1b5;margin-top:6px;padding-top:12px!important}.balance{font-size:15px;font-weight:700}.bottom{display:flex;gap:38px;border-top:1px solid #d9dadd;margin-top:36px;padding-top:18px}.bottom>div{flex:1}.body{white-space:pre-line;line-height:1.5;color:#555}.tax{font-size:10px;color:#777;margin-top:7px}.thanks{text-align:center;color:#999;font-size:9px;margin-top:30px}
 </style></head><body><div class="page"><div class="top"><div>${logo}<div class="brand">${esc(brand.displayName||"")}</div><div class="contact">${brand.address?`<div>${esc(brand.address)}</div>`:""}${brand.email?`<div>${esc(brand.email)}</div>`:""}${brand.phone?`<div>${esc(brand.phone)}</div>`:""}${brand.website?`<div>${esc(brand.website)}</div>`:""}</div>${brand.gstNumber?`<div class="tax">GST/HST # ${esc(brand.gstNumber)}</div>`:""}</div><div class="doctype"><h1>${typeLabel(doc.type)}</h1><div class="number"># ${esc(doc.number||"")}</div><div class="date">Date: ${esc(doc.date||"")}</div>${doc.dueDate?`<div class="date">Due: ${esc(doc.dueDate)}</div>`:""}</div></div><div class="rule"></div><div class="info"><div><div class="label">Bill to</div><div class="bill"><b>${esc(customer.name||"")}</b>${customer.address?`<div>${esc(customer.address)}</div>`:""}${customer.email?`<div>${esc(customer.email)}</div>`:""}${customer.phone?`<div>${esc(customer.phone)}</div>`:""}</div></div><div class="job">${doc.title?`<div class="label">Job</div><div class="jobtitle">${esc(doc.title)}</div>`:""}${doc.notes?`<div class="jobnote">${esc(doc.notes)}</div>`:""}</div></div><table><thead><tr><th>Description</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Amount</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div><span>Subtotal</span><span>${money(t.subtotal)}</span></div>${gst}${pst}<div class="grand"><span>Total</span><span>${money(t.total)}</span></div>${doc.type==="invoice"?`<div><span>Paid</span><span>${money(t.paid)}</span></div><div class="balance"><span>Balance Due</span><span>${money(t.balance)}</span></div>`:""}</div><div class="bottom"><div><div class="label">Notes / Terms</div><div class="body">${esc(brand.defaultPaymentTerms||"")}</div></div><div><div class="label">Payment</div><div class="body">${esc(brand.defaultPaymentInstructions||"")}</div></div></div><div class="thanks">Thank you for your business.</div></div></body></html>`;
}

export async function shareDocument(state,doc){
 const {uri}=await Print.printToFileAsync({html:documentHtml(state,doc)});
 if(await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri,{mimeType:"application/pdf",dialogTitle:`Share ${doc.number}`});
 return uri;
}
