import React,{useEffect,useState} from "react";
import {SafeAreaView,View,Text,ScrollView,TouchableOpacity,Modal,Alert,StyleSheet,StatusBar} from "react-native";
import {loadState,saveState} from "./src/lib/store";
import {money,documentTotals,jobSummary,yearSummary} from "./src/lib/calc";
import {shareDocument} from "./src/lib/pdf";
import {H1,H2,Small,Card,Button,Row,Pill,C} from "./src/components/ui";
import InvoiceSimpleDocForm from "./src/components/InvoiceSimpleDocForm";

const TABS=["Home","Jobs","Sales","Expenses","Mileage","Reports","More"];
const labelType=t=>({invoice:"Invoice",estimate:"Estimate",change_order:"Change Order"}[t]||t);

export default function App(){
 const [state,setState]=useState(null),[tab,setTab]=useState("Home"),[modal,setModal]=useState(null);
 useEffect(()=>{loadState().then(setState)},[]);useEffect(()=>{if(state)saveState(state)},[state]);
 if(!state)return <SafeAreaView style={z.center}><Text>Loading Forsyth Business…</Text></SafeAreaView>;
 const brand=state.brands.find(b=>b.id===state.activeBrandId)||state.brands[0];
 return <SafeAreaView style={z.safe}><StatusBar barStyle="dark-content"/><View style={z.header}><View><Text style={z.tag}>{brand?.division}</Text><Text style={z.brand}>{brand?.displayName}</Text></View></View><ScrollView contentContainerStyle={z.content}>{tab==="Home"&&<Home state={state} setModal={setModal}/>} {tab==="Jobs"&&<Jobs state={state}/>} {tab==="Sales"&&<Sales state={state} setState={setState} setModal={setModal}/>} {tab==="Expenses"&&<Expenses state={state}/>} {tab==="Mileage"&&<Mileage state={state}/>} {tab==="Reports"&&<Reports state={state}/>} {tab==="More"&&<More state={state}/>}</ScrollView><View style={z.nav}>{TABS.map(x=><TouchableOpacity key={x} style={z.navCell} onPress={()=>setTab(x)}><Text style={[z.navText,tab===x&&z.navOn]}>{x}</Text></TouchableOpacity>)}</View>{modal?.kind==="doc"&&<Modal transparent animationType="slide" onRequestClose={()=>setModal(null)}><View style={z.back}><View style={z.sheet}><View style={z.sheetHead}><Text style={z.sheetTitle}>New {labelType(modal.type)}</Text><TouchableOpacity onPress={()=>setModal(null)}><Text style={z.close}>Close</Text></TouchableOpacity></View><ScrollView contentContainerStyle={{paddingBottom:50}}><InvoiceSimpleDocForm state={state} setState={setState} type={modal.type} close={()=>setModal(null)}/></ScrollView></View></View></Modal>}</SafeAreaView>;
}
function Home({state,setModal}){const y=yearSummary(state);return <><H1>Today</H1><Small>Fast quoting, invoicing and job numbers.</Small><View style={z.grid}><Metric l="Revenue" v={money(y.revenue)}/><Metric l="Expenses" v={money(y.expenses)}/><Metric l="Net before tax" v={money(y.net)}/><Metric l="A/R" v={money(y.ar)}/></View><H2>Quick actions</H2><View style={z.actions}><Action t="+ Invoice" f={()=>setModal({kind:"doc",type:"invoice"})}/><Action t="+ Estimate" f={()=>setModal({kind:"doc",type:"estimate"})}/><Action t="+ Change order" f={()=>setModal({kind:"doc",type:"change_order"})}/></View><H2>Active jobs</H2>{state.jobs.filter(j=>j.status==="active").map(j=><JobCard key={j.id} state={state} job={j}/>)}</>}
const Metric=({l,v})=><Card style={z.metric}><Small>{l}</Small><Text style={z.metricVal}>{v}</Text></Card>;
const Action=({t,f})=><TouchableOpacity onPress={f} style={z.action}><Text style={z.actionText}>{t}</Text></TouchableOpacity>;
function Jobs({state}){return <><H1>Jobs</H1><Small>Sales, costs and profit by job.</Small>{state.jobs.map(j=><JobCard key={j.id} state={state} job={j}/>)}</>}
function JobCard({state,job}){const c=state.customers.find(x=>x.id===job.customerId),q=jobSummary(state,job.id);return <Card><View style={z.space}><View style={{flex:1}}><Text style={z.cardTitle}>{job.name}</Text><Small>{c?.name}</Small></View><Pill text={job.status}/></View><View style={z.three}><Mini l="Sales" v={money(q.revenue)}/><Mini l="Costs" v={money(q.directCosts)}/><Mini l="Profit" v={money(q.profit)}/></View></Card>}
const Mini=({l,v})=><View style={{flex:1}}><Small>{l}</Small><Text style={z.mini}>{v}</Text></View>;
function Sales({state,setState,setModal}){return <><H1>Sales</H1><Small>Create and send professional documents without accounting-menu clutter.</Small><View style={[z.actions,{marginTop:14}]}><Action t="+ Invoice" f={()=>setModal({kind:"doc",type:"invoice"})}/><Action t="+ Estimate" f={()=>setModal({kind:"doc",type:"estimate"})}/><Action t="+ Change" f={()=>setModal({kind:"doc",type:"change_order"})}/></View><H2>Documents</H2>{state.documents.slice().reverse().map(d=><DocumentCard key={d.id} d={d} state={state} setState={setState}/>)}</>}
function DocumentCard({d,state,setState}){const job=state.jobs.find(j=>j.id===d.jobId),c=state.customers.find(x=>x.id===job?.customerId),t=documentTotals(d,state.settings);const share=async()=>{try{await shareDocument(state,d)}catch(e){Alert.alert("Could not create PDF",String(e.message||e))}};const sent=()=>setState({...state,documents:state.documents.map(x=>x.id===d.id?{...x,status:"sent"}:x)});const accept=()=>setState({...state,documents:state.documents.map(x=>x.id===d.id?{...x,status:"accepted"}:x)});return <Card><View style={z.space}><View><Text style={z.cardTitle}>{labelType(d.type)} {d.number}</Text><Small>{c?.name} · {job?.name}</Small></View><Pill text={d.status}/></View><Text style={z.big}>{money(t.total)}</Text><Small>Subtotal {money(t.subtotal)} · GST {money(t.gst)} · PST {money(t.pst)}</Small>{d.type==="invoice"&&<Small>Balance {money(t.balance)}</Small>}<View style={z.inline}><Button title="PDF / Share" kind="soft" small onPress={share}/>{d.status==="draft"&&<Button title="Mark sent" small onPress={sent}/>} {d.type==="estimate"&&d.status==="sent"&&<Button title="Accept" small onPress={accept}/>}</View></Card>}
function Expenses({state}){const net=state.expenses.reduce((s,e)=>s+Number(e.netAmount||e.amount||0),0);return <><H1>Expenses</H1><Card><Row label="Business expenses" value={money(net)}/></Card>{state.expenses.slice().reverse().map(e=><Card key={e.id}><View style={z.space}><Text style={z.cardTitle}>{e.vendor}</Text><Text style={z.cardTitle}>{money(Number(e.netAmount||e.amount||0)+Number(e.gst||0)+Number(e.pst||0))}</Text></View><Small>{e.category} · {e.date}</Small></Card>)}</>}
function Mileage({state}){const km=state.mileage.reduce((s,m)=>s+Number(m.km||0),0);return <><H1>Mileage</H1><Card><Text style={z.big}>{km} km</Text><Small>Stored business mileage · {money(km*Number(state.settings.mileageRate||0))} at your current rate.</Small></Card>{state.mileage.slice().reverse().map(m=><Card key={m.id}><View style={z.space}><Text style={z.cardTitle}>{m.purpose}</Text><Text style={z.cardTitle}>{m.km} km</Text></View></Card>)}</>}
function Reports({state}){const y=yearSummary(state);return <><H1>Reports</H1><Card><Row label="Revenue" value={money(y.revenue)}/><Row label="Expenses" value={money(y.expenses)}/><Row label="Net income" value={money(y.net)} bold/></Card><H2>Sales tax</H2><Card><Row label="GST collected" value={money(y.gstCollected)}/><Row label="GST paid / ITCs" value={money(y.gstITC)}/><Row label="GST net" value={money(y.gstNet)} bold/><Row label="PST collected" value={money(y.pstCollected)}/></Card></>}
function More({state}){return <><H1>More</H1><H2>Business profiles</H2>{state.brands.map(b=><Card key={b.id}><Text style={z.cardTitle}>{b.displayName}</Text><Small>{b.legalName}</Small></Card>)}<H2>Pricing defaults</H2><Card><Row label="Labour" value={`${money(state.settings.labourRate)}/hr`}/><Row label="Helper" value={`${money(state.settings.helperRate)}/hr`}/><Row label="Mileage" value={`${money(state.settings.mileageRate)}/km`}/><Row label="Material markup" value={`${state.settings.defaultMaterialMarkupPct}%`}/></Card></>}
const z=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},center:{flex:1,alignItems:"center",justifyContent:"center"},header:{backgroundColor:"#fff",paddingHorizontal:17,paddingVertical:12,borderBottomWidth:1,borderBottomColor:C.line},tag:{fontSize:10,fontWeight:"900",letterSpacing:1,color:C.muted,textTransform:"uppercase"},brand:{fontSize:18,fontWeight:"900",color:C.ink},content:{padding:17,paddingBottom:105},grid:{flexDirection:"row",flexWrap:"wrap",gap:9,marginTop:15},metric:{width:"48%"},metricVal:{fontSize:20,fontWeight:"900",marginTop:5},actions:{flexDirection:"row",flexWrap:"wrap",gap:8},action:{backgroundColor:C.ink,borderRadius:12,paddingHorizontal:14,paddingVertical:13},actionText:{color:"#fff",fontWeight:"900"},cardTitle:{fontSize:16,fontWeight:"900",color:C.ink},big:{fontSize:27,fontWeight:"900",marginTop:12},space:{flexDirection:"row",justifyContent:"space-between",gap:10},three:{flexDirection:"row",gap:8,marginTop:14},mini:{fontWeight:"900",fontSize:15,marginTop:3},inline:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:12},nav:{position:"absolute",bottom:0,left:0,right:0,backgroundColor:"#fff",borderTopWidth:1,borderTopColor:C.line,flexDirection:"row",paddingVertical:7},navCell:{flex:1,alignItems:"center",paddingVertical:7},navText:{fontSize:9.5,fontWeight:"800",color:"#7A838C"},navOn:{color:C.ink,fontWeight:"900"},back:{flex:1,justifyContent:"flex-end",backgroundColor:"rgba(0,0,0,.32)"},sheet:{maxHeight:"94%",backgroundColor:C.bg,borderTopLeftRadius:22,borderTopRightRadius:22,padding:17},sheetHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:14},sheetTitle:{fontSize:21,fontWeight:"900"},close:{fontWeight:"900"}});
